spark.master                                           spark://spark-master:7077

# ============================================================
# Iceberg
# ============================================================

spark.sql.extensions                                   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

spark.sql.defaultCatalog                               rest

spark.sql.catalog.rest                                 org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.rest.type                            rest
spark.sql.catalog.rest.uri                             http://iceberg:8181
spark.sql.catalog.rest.warehouse                       s3://warehouse/

# ============================================================
# FileIO
# ============================================================

spark.sql.catalog.rest.io-impl                         org.apache.iceberg.aws.s3.S3FileIO

# ============================================================
# MinIO (Iceberg S3FileIO)
# ============================================================

spark.sql.catalog.rest.s3.endpoint                     http://minio:9000
spark.sql.catalog.rest.s3.path-style-access            true
spark.sql.catalog.rest.s3.region                       us-east-1
spark.sql.catalog.rest.s3.access-key-id                admin
spark.sql.catalog.rest.s3.secret-access-key            password1234

# ============================================================
# Hadoop S3A
# ============================================================

spark.hadoop.fs.s3a.endpoint                           http://minio:9000
spark.hadoop.fs.s3a.access.key                         ${env.MINIO_ROOT_USER}
spark.hadoop.fs.s3a.secret.key                         ${env.MINIO_ROOT_PASSWORD}
spark.hadoop.fs.s3a.path.style.access                  true
spark.hadoop.fs.s3a.connection.ssl.enabled             false
spark.hadoop.fs.s3a.aws.credentials.provider           org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.impl                               org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint.region                    us-east-1

# ============================================================
# AWS SDK
# ============================================================

spark.driver.extraJavaOptions                          -Daws.region=us-east-1
spark.executor.extraJavaOptions                        -Daws.region=us-east-1

# ============================================================
# Optional
# ============================================================

# spark.sql.catalog.rest.cache-enabled                 false
